- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: create a kevyault secret
    azure_rm_keyvaultsecret:
      keyvault_uri: https://tmpkeyvault.vault.azure.net
      secret_name: playsecret
      secret_value: 'mysecret'
      tags:
        testing: play
        delete: on-exit
