- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: create a kevyault key
    azure_rm_keyvaultkey:
      keyvault_uri: https://tmpkeyvault.vault.azure.net
      key_name: playkey
      tags:
        testing: play
        delete: on-exit
