- hosts: localhost
  connection: local
  gather_facts: no
  tasks:
  - name: delete a kevyault key
    azure_rm_keyvaultkey:
      keyvault_uri: https://tmpkeyvault.vault.azure.net
      state: absent
      key_name: playkey
